### ISSUE TITLE
Travis is broken

### ISSUE THREAD

**Issue by yn-coder** [postpdm/ich_bau#125]

**Comment by yn-coder** [comment]
`ValueError: pipenv requires an #egg fragment for version controlled dependencies. Please install remote dependency in the form git+https://github.com/yn-coder/django-bootstrap3-datetimepicker.git#egg=<package-name>.`

**Comment by yn-coder** [comment]
`

............................................................F..........E...
======================================================================
ERROR: test_SVN_Client (project.test_svn_wrapper.SVN_Wrapper_Temp_Dir_Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/circleci-ich-bau/project/test_svn_wrapper.py", line 111, in test_SVN_Client
    self.assertEqual( file_path_ulr, r.info()['url'] )
  File "/home/circleci/circleci-ich-bau/.venv/lib/python3.6/site-packages/svn/common.py", line 77, in info
    root = xml.etree.ElementTree.fromstring(result)
  File "/usr/local/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

======================================================================
FAIL: test_SVN_Wrapper (project.test_svn_wrapper.SVN_Wrapper_Client_Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/circleci-ich-bau/project/test_svn_wrapper.py", line 155, in test_SVN_Wrapper
    self.assertTrue( info[0] == VCS_REPO_SUCCESS )
AssertionError: False is not true

----------------------------------------------------------------------
Ran 75 tests in 10.239s

FAILED (failures=1, errors=1)
Destroying test database for alias 'default'...
Exited with code 1
`

**Comment by yn-coder** [comment]
may be OS.join is needed?

**Comment by yn-coder** [comment]
`Unable to save test results from /home/circleci/circleci_ich_bau/test-results
Error stat /home/circleci/circleci_ich_bau/test-results: no such file or directory
Found no path with test results, skipping`

**Comment by yn-coder** [comment]
https://circleci.com/docs/2.0/language-python/

**Comment by yn-coder** [comment]
two_folders_up

**Comment by yn-coder** [comment]
Traivis is back
