### ISSUE TITLE
Test file repo protocol on travis

### ISSUE THREAD

**Issue by yn-coder** [postpdm/ich_bau#99]
Test file repo protocol on travis

#33 #35

**Comment by yn-coder** [comment]
> ERROR: test_SVN_Client (project.test_svn_wrapper.SVN_Wrapper_Temp_Dir_Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/postpdm/ich_bau/project/test_svn_wrapper.py", line 89, in test_SVN_Client
    print( r.info() )
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/svn/common.py", line 80, in info
    do_combine=True)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/svn/common.py", line 54, in run_command
    return self.external_command(cmd, environment=self.__env, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/svn/common_base.py", line 34, in external_command
    p.returncode, cmd, stdout))
svn.exception.SvnException: Command failed with (1): ['svn', '--non-interactive', '--username', '', '--password', '', '--no-auth-cache', 'info', '--xml', '/tmp/tmp8t_bsb86test_repo_name']
b'<?xml version="1.0" encoding="UTF-8"?>\n<info>\nsvn: E155007: \'/tmp/tmp8t_bsb86test_repo_name\' is not a working copy\n'

**Comment by yn-coder** [comment]
> b'<?xml version="1.0" encoding="UTF-8"?>\n<info>\nsvn: E155007: \'/tmp/tmpws8b9rpd/test_repo_name\' is not a working copy\n'

**Comment by yn-coder** [comment]
Yes, it's true - folder is not working copy

**Comment by yn-coder** [comment]
You need path for svnadmin and **url** for svn client

**Comment by yn-coder** [comment]
got it!

**Comment by yn-coder** [comment]
ERROR: test_Overwrite_Settings_File_Protocol (project.test_svn_wrapper.SVN_Wrapper_Overwrite_Settings)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/postpdm/ich_bau/project/test_svn_wrapper.py", line 124, in test_Overwrite_Settings_File_Protocol
    "REPO_BASE_URL" : pathlib.Path( path ).as_uri(),
  File "/opt/python/3.6.3/lib/python3.6/pathlib.py", line 719, in as_uri
    raise ValueError("relative path can't be expressed as a file URI")
ValueError: relative path can't be expressed as a file URI
